server:
 port: 8080

# Component Info
info:
 component: Spring Cloud Zuul Server

# Define Routes
zuul:
  routes:
    zuulserver: /self/**
#    stores: /stores/**
#    customers: /customers/**

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 8000

# Spring Boot Actuator
management:
  # Management Path
  context-path: /admin
  # Disable security on actuator endpoint
  security:
    enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false # sensitive endpoints will require a username/password when they are accessed over HTTP (or simply disabled if web security is not enabled)

logging:
  level:
    demo: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
