server:
 port: 8888

# Component Info
info:
 component: Spring Config Server

# Spring Boot Actuator Management Path
management:
  context-path: /admin
  # Disable security on actuator endpoint
  security:
    enabled: false

# Spring properties
spring:
 # Spring Cloud Config Server Repository
 cloud:
  config:
   server:
    git:
      uri: https://github.com/juanmrm/spring-cloud-netflixoss
      searchPaths: config-repo

logging:
  level:
    com.netflix.discovery: INFO
    org.springframework.cloud: INFO

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health

